# Generated by Django 5.2 on 2025-04-27 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True,
                        help_text="Выберете дату и время начала привычки",
                        null=True,
                        verbose_name="Время начала выполнения привычки",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Опишите привычку",
                        max_length=255,
                        verbose_name="Действие привычки",
                    ),
                ),
                (
                    "is_habit_nice",
                    models.BooleanField(
                        default=False,
                        help_text="Приятная ли привычка",
                        verbose_name="Признак прятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.SmallIntegerField(
                        default=1, verbose_name="Периодичность (в днях) - от 1 до 7"
                    ),
                ),
                (
                    "prize",
                    models.CharField(
                        blank=True,
                        help_text="Опишите вознаграждение",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.SmallIntegerField(
                        help_text="Укажите время на выполнение привычки в секундах",
                        verbose_name="Время на выполнение прывычки",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Опубликовать привычку",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "is_related",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите связанную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habit.habit",
                        verbose_name="Связання привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
